import { CastMember, Nomination, GalleryItem, VideoMoment, TimelineEvent, MovieQuote } from "./types";

export const MOVIE_INFO = {
  title: "THE LAST FRIDAY",
  tagline: "In a system built on silence, truth is a death sentence.",
  synopsis: "When a desperate young woman seeks help from the son of a powerful senator, she is pulled into a night of brutality that spirals into a calculated massacre. As the crime is buried beneath corruption, power, and silence, a determined detective risks everything to expose a conspiracy that was never meant to be uncovered. Inspired by true events and intensified through fiction, The Last Friday is a gripping action thriller about survival, corruption, and the deadly cost of truth.",
  shortSynopsis: "When a young woman seeks help from the son of a powerful senator, she is drawn into a night of unimaginable violence. As the crime is covered up through influence and fear, a relentless detective begins uncovering a web of corruption that reaches the highest levels of power.",
  genre: "Action Thriller",
  runtime: "89 Minutes",
  language: "English",
  country: "Nigeria",
  director: "Gedion Spice",
  productionStudio: "Back to Life Entertainment LLC",
  releaseInfo: "2026 (Theatrical & Streaming)",
  rating: "R (Intense Violence, Language)",
  bannerImage: "/images/hero_banner_background_1782315440066.jpg",
  posterImage: "/images/movie_poster_1782315458025.jpg",
  trailerEmbedUrl: "https://www.youtube.com/embed/elD1V6_A7ks",
  themes: ["Justice", "Survival", "Corruption", "Resilience", "Truth"],
};

export const CAST_MEMBERS: CastMember[] = [
  {
    id: "cast-1",
    name: "Jamilaah Ibrahim",
    role: "Tricia",
    imageUrl: "/images/jamilaah.jpg",
    nomination: "Best Actress (Africa)",
  },
  {
    id: "cast-2",
    name: "Temple Ikechukwu",
    role: "Ona",
    imageUrl: "/images/temple.jpg",
    nomination: "Best Supporting Actor (Africa)",
  },
  {
    id: "cast-3",
    name: "Jide Bolarinwa",
    role: "Senator Kenedy",
    imageUrl: "/images/jide.jpg",
    nomination: "Best Supporting Actor (Africa)",
  },
  {
    id: "cast-4",
    name: "Hoom'Suk Alex Jibrin",
    role: "Detective Tony",
    imageUrl: "/images/hoomsuk.jpg",
    nomination: "Best Actor (Africa)",
  },
  {
    id: "cast-5",
    name: "Mickey Odey",
    role: "Paulo",
    imageUrl: "/images/mickey.jpg",
    nomination: "Best Actor (Africa)",
  },
  {
    id: "cast-6",
    name: "Promise Binang Eyare",
    role: "Joan",
    imageUrl: "/images/promise.jpg",
    nomination: "Best Actress (Nollywood)",
  },
];

export const NOMINATIONS: Nomination[] = [
  {
    id: "nom-1",
    category: "Best African Film",
    description: "Honoring outstanding cinematic quality, narrative power, and production value on the African continent.",
  },
  {
    id: "nom-2",
    category: "Best African Drama",
    description: "Recognizing high emotional stakes, intense acting performances, and deep storytelling craft.",
  },

  {
    id: "nom-4",
    category: "Best Actress (Africa)",
    nominee: "Jamilaah Ibrahim",
    description: "Applauding a powerhouse performance — the emotional core of a film built on survival, courage, and the fight for justice.",
  },
  {
    id: "nom-5",
    category: "Best Actress (Nollywood)",
    nominee: "Promise Binang Eyare",
    description: "A compelling Nollywood performance that grounds the film's themes of witness, truth-telling, and resilience.",
  },
  {
    id: "nom-6",
    category: "Best Supporting Actor (Africa)",
    nominee: "Temple Ikechukwu",
    description: "Capturing the complex layers of complicity and menace in a standout supporting performance.",
  },
  {
    id: "nom-7",
    category: "Best Supporting Actor (Africa)",
    nominee: "Jide Bolarinwa",
    description: "Establishing a chilling, larger-than-life political antagonist that defines the film's central conflict.",
  },
  {
    id: "nom-8",
    category: "Best Actor (Africa)",
    nominee: "Hoom'Suk Alex Jibrin",
    description: "A riveting portrayal of Detective Danjuma — the unrelenting investigator who refuses to let the truth stay buried.",
  },
  {
    id: "nom-9",
    category: "Best Actor (Africa)",
    nominee: "Mickey Odey",
    description: "A nuanced, powerful performance that brings depth and moral weight to one of the film's most pivotal roles.",
  },
  {
    id: "nom-10",
    category: "Best Producer",
    nominee: "Anthony A. Uzuakpunwa",
    description: "Recognizing the vision, tenacity, and craft behind producing one of TINFF 2026's most compelling Nigerian features.",
  },
  {
    id: "nom-11",
    category: "Best Original Music Score International",
    description: "Celebrating the evocative, tension-filled original score of The Last Friday that heightens every thrill and dramatic moment.",
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Official Movie Poster",
    type: "poster",
    imageUrl: "/images/movie_poster_1782315458025.jpg",
  },
  {
    id: "gal-2",
    title: "Paulo's Confrontation",
    type: "still",
    imageUrl: "/images/gallery_1.jpg",
  },
  {
    id: "gal-3",
    title: "The Escape Attempt",
    type: "still",
    imageUrl: "/images/gallery_2.jpg",
  },
  {
    id: "gal-4",
    title: "The Interview",
    type: "still",
    imageUrl: "/images/gallery_3.jpg",
  },
  {
    id: "gal-5",
    title: "The Chase",
    type: "still",
    imageUrl: "/images/gallery_4.jpg",
  },
  {
    id: "gal-6",
    title: "Tricia's Stand",
    type: "still",
    imageUrl: "/images/gallery_5.jpg",
  },
];

export const VIDEO_MOMENTS: VideoMoment[] = [
  {
    id: "vid-1",
    title: "The Night It Began",
    clipKey: "beginning",
    description: "One desperate young woman's search for help spirals into an unforgettable night of brutal violence that will change everything.",
    duration: "0:45",
    thumbnailUrl: "https://images.unsplash.com/photo-1518173946687-a4c8a383392e?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "vid-2",
    title: "The Cover-Up",
    clipKey: "betrayal",
    description: "Powerful political figures move swiftly. Phones ring. Favors are called in. The machinery of corruption silences every witness.",
    duration: "1:12",
    thumbnailUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "vid-3",
    title: "The Detective",
    clipKey: "fire",
    description: "Detective Tony follows a trail of lies no one else dares to touch — and discovers a conspiracy that goes all the way to the top.",
    duration: "1:05",
    thumbnailUrl: "https://images.unsplash.com/photo-1542224566-6e85f2e6772f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "vid-4",
    title: "The Truth Surfaces",
    clipKey: "revenge",
    description: "As the evidence mounts and threats escalate, a survivor and a detective forge an unbreakable alliance against impossible odds.",
    duration: "1:30",
    thumbnailUrl: "/images/hero_banner_background_1782315440066.jpg",
  },
  {
    id: "vid-5",
    title: "The Last Friday",
    clipKey: "last-friday",
    description: "Revenge has a deadline. Every secret has a cost. Every betrayal has consequences. It all ends on The Last Friday.",
    duration: "2:00",
    thumbnailUrl: "/images/action_scene_still_1782315520243.jpg",
  },
];

export const MOVIE_QUOTES: MovieQuote[] = [
  {
    id: "quote-1",
    text: "They said nobody would believe me. They were right. Until he did.",
    speaker: "Tricia",
    context: "On finding Detective Tony",
  },
  {
    id: "quote-2",
    text: "The most dangerous thing a powerful man can do is underestimate a desperate woman.",
    speaker: "Detective Tony",
    context: "To his superior during the investigation",
  },
  {
    id: "quote-3",
    text: "Silence is not peace. Silence is just another word for control.",
    speaker: "Tricia",
    context: "Testifying against the cover-up",
  },
  {
    id: "quote-4",
    text: "You buried the truth. But the truth has a way of clawing its way back to the surface. Every. Single. Time.",
    speaker: "Detective Tony",
    context: "Confronting Senator Kenedy",
  },
  {
    id: "quote-5",
    text: "Revenge has a deadline. And mine... is this Friday.",
    speaker: "Tricia",
    context: "The final act",
  },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "time-1",
    phase: "Phase 01",
    title: "Movie Development & Scripting",
    description: "Script created by award-winning screenwriters capturing the heartbeat of Lagos, blending grit and intense character-driven drama.",
    date: "Late 2024",
    status: "completed",
  },
  {
    id: "time-2",
    phase: "Phase 02",
    title: "Principal Photography in Lagos",
    description: "High-octane filming on location in Lagos, Nigeria. Groundbreaking choreography, practical stunts, and hyper-stylized lighting.",
    date: "Mid 2025",
    status: "completed",
  },
  {
    id: "time-3",
    phase: "Phase 03",
    title: "Official Selection – TINFF",
    description: "Honored with the prestigious laurel of Official Selection at the Toronto International Nollywood Film Festival.",
    date: "May 2026",
    status: "completed",
  },
  {
    id: "time-4",
    phase: "Phase 04",
    title: "10 Official TINFF@10 Nominations",
    description: "The Last Friday earns 10 official nominations at TINFF's historic 10th Anniversary Edition — including Best African Film, Best African Drama, Best Actress (Africa), Best Actress (Nollywood), Best Supporting Actor (Africa) x2, Best Actor (Africa) x2, Best Producer, and Best Original Music Score International.",
    date: "June 2026",
    status: "current",
  },
  {
    id: "time-5",
    phase: "Phase 05",
    title: "TINFF World Premiere",
    description: "The official first screening of The Last Friday to international festival crowds, judges, and press in Toronto, Canada.",
    date: "September 2026",
    status: "upcoming",
  },
  {
    id: "time-6",
    phase: "Phase 06",
    title: "Global Theatrical & Streaming Release",
    description: "Bringing the war to the global stage. Released in theatres nationwide and premium international streaming networks.",
    date: "November 2026",
    status: "upcoming",
  },
];

export const EPK_INFO = {
  logline: "A desperate young woman’s search for help leads to a brutal crime tied to political power, forcing a determined detective to risk everything to expose a deadly conspiracy buried in silence.",
  directorsStatement: "The Last Friday is rooted in real experiences that reflect the abuse of power and the silence that often protects it. This story was born from a need to confront that silence and give voice to truths that are often buried.\n\nAt its core, the film explores justice, survival, and the cost of truth. Through Joan, we witness resilience in the face of fear. Through Detective Tony, we follow the pursuit of justice against overwhelming political pressure. Through Tricia, we see the moment when silence transforms into action.\n\nThis film is not just a thriller—it is a statement about power, accountability, and what happens when truth refuses to stay hidden.\n\n— Gedion Spice",
  directorBio: "Gedion Spice (Stephen Gideon Obiajunwa) is an accomplished filmmaker, director, and producer with over 13 years of experience. A graduate of the National Film Institute, he is known for his strong visual storytelling and compelling narratives.\n\nHis work has received international recognition, including nominations at the Africa Magic Viewers’ Choice Awards (AMVCA).",
  technicalSpecs: {
    runtime: "89 minutes",
    country: "Nigeria",
    language: "English",
    genre: "Action Thriller",
    year: "2026",
    camera: "RED Epic Dragon",
    format: "RAW",
    frameRate: "23.976 fps",
    sound: "5.1 Surround",
    aspectRatio: "2.39:1 (CinemaScope)",
  },
  supportingCast: [
    "Agatha Peter — Lucia",
    "Zinta Joel — Doctor Clara",
    "Francis Eunice Ehie — Debbie",
    "Patric Chukwuemeka Chigbo — Tony",
    "Rita Samuel — Ojodoma",
    "Stanley Ikechukwu — Sam",
    "Nasa Bliss — Eucheria",
    "Mercy Aba — Grace",
    "Jethro King Nwadike — Gabe",
    "Zion Sirzee Bissallah — DJ",
    "Edrack Destiny — Party MC",
    "Sam Namo — 1st MC",
    "Francis — 2nd MC",
    "Sule Ganiyu Jessy — Senator P.A.",
    "Amadi Ebuka — Senior Security",
    "Energy Oluko — Security 1",
    "Isu GodsWill Okpani — Security 2",
    "Ukwuru Henry Akira — Security 3",
    "Gabriel Chibuike Obu — Security 4",
    "Maria Ugbashi — Brenda",
    "Terry A’wase — Ray",
    "Igwe Chikadilli Franka — Rahama",
    "Ruthwealth Swore — Mother",
    "Joshua Monsonyem — East",
    "Victor A. A Zion — Daga",
  ],
  extrasCast: [
    "Ashu Precious Agbo",
    "Obenyi Confidence",
    "Esther Nnamani",
    "Obioma Emmanuel C",
    "Clement M Chiamaka",
    "Wise Emmanuel",
    "Yusuf Monsurat",
    "Bala Immaculate",
    "Adeyemi Nurudan",
    "Ifeanyi Victor",
    "Chigozie Ohakamma",
    "Jennifer Joseph",
    "Yunana Hassan",
    "Sam Johnathan",
    "Success M Favor",
    "Japheth Light Christopher",
    "Zahara A Samala",
    "Fatima Yunana",
    "David M Okorie",
    "Emmanuel John",
  ],
  specialRoles: {
    policeOfficers: [
      "Troy G. Udoysun",
      "Arnold Taiwo",
      "Shinkut Micheal Shabanyan",
    ],
    biker: "Ogoja Justice",
    hospitalExtras: [
      "Oluchi T Samuel",
      "Ogbole Faith Aisha",
      "Happiness Nathaniel",
      "Goodness Edwin",
      "Ephraim Abiaje",
      "Ossai Unoma Ruth",
      "Busayo Kayode",
    ],
    interviewer: "Uju Faith Edeh",
    assassins: [
      "Jessy Sule Ganiyu",
      "Okpala Chidolue",
      "Abdullateef Ismail",
    ]
  },
  keyCrew: {
    "Director": "Gedion Spice",
    "Executive Producer / Producer": "Anthony Uzuakpunwa",
    "Writers": "Edrah Destiny, Percy Macdonald",
    "Director of Photography": "Theophilus Anegba, Eddie George",
    "Editor / Colorist": "Anthony Azcarate",
    "Editor": "Solomon M. Hunde",
    "Assistant Director": "Obed Emmanuel",
    "Casting": "Olisa Ogbogu",
    "Props": "Dyiltu Joan",
    "Location Driver": "Doctor White",
    "Welfare": "Gloria Ezeh, Dazy Mary David",
    "Script Supervisor / Continuity": "Magnifique Ecirvaine, Joy Ngene",
    "Makeup": "Modom Mercy, Loveth Usman",
    "Makeup Assist / Special Effects": "Precious Ashu Agbu",
    "Costume": "DecostumePlaceAbuja",
    "Set Design": "Emmanuel Akachukwu Emmanuel, Samuel Emeka Kingsley",
    "Sound": "Kelvin Asukwo, Femi Abayomi",
    "Sound Assistant": "Success Charlle",
    "Sound Effects": "Leo B Okwese (DGN)",
    "Sound Scoring": "Peter Kwembe",
    "Gaffer": "Richman Oliver Efe (late), Ophirsand Set",
    "Production Assistants": "David M. Okorie (Prof.D), John Emmanuel, Throne Nandom Micheal",
    "Location Manager": "Zion Sirzee Bissallah",
    "Stunts Instructor": "Energy Oluko",
    "Logistics Manager": "Nathan Branden",
    "Music": "Frankie Milli, Gloriahannas, Flow",
  },
  festivals: [
    "Africa Films for Impact Festival",
    "Silicon Valley African Film Festival",
    "African Diaspora Cinema Festival",
    "Zimbabwe International Film Festival",
    "Essence Film Festival",
    "Bantu Film Festival",
    "Pan African Film Festival",
    "Toronto Black Film Festival",
    "Montreal International Film Festival",
  ],
  specialThanks: [
    "Royalton Hospital",
    "Bala Yaye",
    "Base University Hospital",
    "BrookVille Hotel",
    "Dorothy Njemanze Foundation",
    "Randy Johnson",
  ],
  contact: {
    company: "Back to Life Entertainment LLC",
    address: "Los Angeles, California, USA / Abuja, Nigeria",
    contactPerson: "Anthony Uzuakpunwa",
    role: "Executive Producer / Producer",
    phone: "424-356-3825",
    email: "backtolifeentertainment@gmail.com",
  }
};
